=== benhar-dev/tchmi-multi-screen/twincat-hmi-project/Packages/Beckhoff.TwinCAT.HMI.Framework.12.744.3/runtimes/native1.12-tchmi/Schema/TchmiConfig.Schema.json
{
   "$schema": "http://json-schema.org/draft-04/schema#",
   "type": "object",
   "properties": {
      "$schema": {
         "type": "string",
         "description": "URL to a schema file"
      },
      "basePath": {
         "type": "string",
         "description": "Path to the Framework Directory."
      },
      "dependencyFiles": {
         "type": "array",
         "description": "Theme independent files.",
         "items": {
            "type": "object",
            "properties": {
               "name": {
                  "type": "string",
                  "description": "Path to the file",
                  "minLength": 1
               },
               "type": {
                  "type": "string",
                  "enum": [ "Stylesheet", "JavaScript" ],
                  "description": "Type of file."
               },
               "description": {
                  "type": "string",
                  "description": "A long description of this file."
               }
            },
            "required": [ "name", "type" ]
         }
      },
      "activeTheme": {
         "type": "string",
         "minLength": 1,
         "description": "Name of the Theme which is active while loading the Application."
      },
      "themes": {
         "description": "List of Themes of this Application.",
         "type": "object",
         "additionalProperties": {
            "description": "Definition of the Theme.",
            "type": "object",
            "properties": {
               "resources": {
                  "description": "References to Resources of this Theme.",
                  "type": "array",
                  "items": {
                     "type": "object",
                     "properties": {
                        "name": {
                           "type": "string",
                           "description": "Path to the file",
                           "minLength": 1
                        },
                        "type": {
                           "type": "string",
                           "enum": [ "Stylesheet", "ThemedValues" ],
                           "description": "Type of the control asset."
                        },
                        "description": {
                           "type": "string",
                           "description": "A long description of this file."
                        }
                     }
                  }
               },
               "replacesThemeForControls": {
                  "type": "array",
                  "description": "Project only: Do not load theme files (.theme and .css) for this controls",
                  "items": {
                     "type": "string"
                  }
               }
            }
         }
      },
      "locale": {
         "type": "string",
         "description": "Deprecated and unused."
      },
      "scaleMode": {
         "type": "string",
         "enum": [ "None", "ScaleToFill", "ScaleToFit", "ScaleToFitWidth", "ScaleToFitHeight" ],
         "description": "Scalemode of the full Application."
      },
      "startupView": {
         "type": "string",
         "description": "Name of the View which is active while loading the Application."
      },
      "loginPage": {
         "type": "string",
         "description": "Path to a custom login page."
      },
      "tcHmiServer": {
         "description": "Configuration of the Server Communication.",
         "type": "object",
         "properties": {
            "websocketIntervalTime": {
               "type": "integer",
               "description": "Interval used for server request or symbols if no override is specified."
            },
            "websocketTimeout": {
               "type": "integer",
               "description": "Timeout used for server requests or symbols if no override is specified."
            },
            "websocketSystemTimeout": {
               "type": "integer",
               "description": "Timeout used for internal server communication. Normally it is not necessary to change this setting."
            },
            "websocketSubscriptionMode": {
               "type": "string",
               "enum": [ "Change", "Poll" ],
               "description": "Subscription mode used for symbol related subscriptions if no override is specified."
            }
         }
      },
      "packages": {
         "description": "List of all available packages.",
         "type": "array",
         "items": {
            "type": "object",
            "properties": {
               "name": {
                  "type": "string",
                  "description": "Package Id."
               },
               "basePath": {
                  "type": "string",
                  "description": "Path to the package root directory."
               }
            }
         }
      },
      "userControls": {
         "description": "List of all available Usercontrols.",
         "type": "array",
         "items": {
            "type": "object",
            "properties": {
               "url": {
                  "type": "string",
                  "description": "Path to the Usercontrol main file."
               }
            },
            "required": [
               "url"
            ]
         }
      },
      "content": {
         "description": "List of all available content files.",
         "type": "array",
         "items": {
            "type": "object",
            "properties": {
               "url": {
                  "type": "string",
                  "description": "Path to the content file."
               },
               "preload": {
                  "type": "boolean",
                  "description": "Defines if the file should be loaded and compiled during initialization to accelerate later usage."
               },
               "keepAlive": {
                  "type": "boolean",
                  "description": "Defines if the compile result should be cached after first usage to accelerate later usage."
               }
            },
            "required": [
               "url",
               "preload"
            ]
         }
      },
      "views": {
         "description": "List of all available view files.",
         "type": "array",
         "items": {
            "type": "object",
            "properties": {
               "url": {
                  "type": "string",
                  "description": "Path to the view file."
               },
               "preload": {
                  "type": "boolean",
                  "description": "Defines if the file should be loaded and compiled during initialization to accelerate later usage."
               },
               "keepAlive": {
                  "type": "boolean",
                  "description": "Defines if the compile result should be cached after first usage to accelerate later usage."
               }
            },
            "required": [
               "url",
               "preload"
            ]
         }
      },
      "userFunctions": {
         "description": "List of all available user function files.",
         "type": "array",
         "items": {
            "type": "object",
            "properties": {
               "url": {
                  "type": "string",
                  "description": "Path to the user function js file."
               }
            }
         }
      },
      "symbols": {
         "type": "object",
         "properties": {
            "internal": {
               "type": "object",
               "additionalProperties": {
                  "type": "object",
                  "properties": {
                     "value": {},
                     "persist": {
                        "type": "boolean"
                     },
                     "readonly": {
                        "type": "boolean"
                     },
                     "type": {
                        "type": "string"
                     }
                  },
                  "required": [
                     "value",
                     "type"
                  ]
               }
            }
         },
         "required": [ "internal" ]
      },
      "trigger": {
         "description": "Definition of global Triggers.",
         "type": "array",
         "items": {
            "$ref": "tchmi:framework#/definitions/Trigger"
         }
      },
      "actionTemplates": {
         "description": "Definition of all available actionTemplates.",
         "type": "array",
         "items": {
            "type": "object",
            "properties": {
               "name": {
                  "description": "Name of the Action Template.",
                  "type": "string"
               },
               "category": {
                  "type": "string"
               },
               "actions": {
                  "type": "array"
               },
               "parameters": {
                  "type": "array",
                  "items": {
                     "type": "object",
                     "properties": {
                        "name": {
                           "type": "string"
                        },
                        "type": {
                           "type": "string"
                        },
                        "description": {
                           "type": "string"
                        },
                        "structDataType": {
                           "type": "string"
                        }
                     }
                  }
               }
            }
         }
      },
      "languages": {
         "description": "List of all available localization files.",
         "type": "object",
         "additionalProperties": {
            "type": "string",
            "description": "Name of the language."
         }
      },
      "languageFallback": {
         "type": "string",
         "description": "Name of the language."
      },
      "keyboardLayouts": {
         "description": "List of available keyboard layouts in project.",
         "type": "array",
         "items": {
            "type": "object",
            "properties": {
               "url": {
                  "type": "string",
                  "description": "Path to the keyboard layout."
               }
            },
            "required": [
               "url"
            ]
         }
      },
      "disableLoadingOptimization": {
         "type": "boolean",
         "description": "Disable various loading optimizations"
      },
      "tcspeech": {
         "type": "object",
         "description": "Configuration for TcSpeech Integration.",
         "properties": {
            "domain": {
               "type": "string",
               "description": "Name of the TcSpeech extension on the server."
            },
            "enableSpeaker": {
               "type": "boolean",
               "description": "Our speaker should be used."
            },
            "enableMicrophone": {
               "type": "boolean",
               "description": "Our microphone should be used."
            },
            "defaultVolume": {
               "type": "number",
               "description": "Default audio volume",
               "default": 1,
               "minimum": 0,
               "maximum": 1
            },
            "confidenceThreshold": {
               "type": "number",
               "description": "Ignore detected speech commands with a lower relative measure of the certainty of correct recognition of a phrase. The value is from 0.0 to 1.0, for low to high confidence, respectively. ",
               "default": 0.2,
               "minimum": 0,
               "maximum": 1
            }
         }
      },
      "creatorSettings": {
         "description": "Definition of engineering settings.",
         "type": "object",
         "properties": {
            "viewport": {
               "description": "Definition of the viewport emulation.",
               "type": "object",
               "properties": {
                  "defaultWidth": {
                     "type": "number",
                     "description": "Width as a Pixel Number."
                  },
                  "defaultHeight": {
                     "type": "number",
                     "description": "Height as a Pixel Number."
                  }
               },
               "required": [ "defaultHeight", "defaultWidth" ]
            }
         },
         "required": [ "viewport" ]
      }
   },
   "additionalProperties": false,
   "required": [
      "basePath",
      "scaleMode",
      "startupView",
      "tcHmiServer",
      "userControls",
      "content",
      "views",
      "userFunctions",
      "symbols",
      "trigger",
      "actionTemplates",
      "languages",
      "creatorSettings"
   ]
}

=== benhar-dev/tchmi-multi-screen/twincat-hmi-project/demo-multi-screen/Properties/tchmiconfig.tpl.json
{
  "$schema": "../../Packages/Beckhoff.TwinCAT.HMI.Framework.12.744.3/runtimes/native1.12-tchmi/Schema/TchmiConfig.Schema.json",
  "basePath": "./framework",
  "scaleMode": "None",
  "startupView": "Desktop.view",
  "loginPage": "",
  "tcHmiServer": {
    "websocketIntervalTime": 500,
    "websocketTimeout": 20000,
    "websocketSystemTimeout": 60000,
    "websocketSubscriptionMode": "Change"
  },
  "activeTheme": "Base",
  "themes": {
    "Base": {
      "resources": [
        {
          "name": "Themes/Base/Base.theme",
          "description": "",
          "type": "ThemedValues"
        },
        {
          "name": "Themes/Base/BaseStyle.css",
          "description": "",
          "type": "Stylesheet"
        }
      ],
      "replacesThemeForControls": []
    }
  },
  "dependencyFiles": [
    {
      "name": "Fonts/Fonts.css",
      "description": "",
      "type": "Stylesheet"
    },
    {
      "name": "Function/LoadViewFromQuery.js",
      "description": "",
      "type": "JavaScript"
    }
  ],
  "userControls": [],
  "content": [],
  "views": [
    {
      "url": "Desktop.view",
      "preload": false,
      "keepAlive": false
    },
    {
      "url": "ExtendedDesktop.view",
      "preload": false,
      "keepAlive": false
    }
  ],
  "userFunctions": [
    {
      "url": "Function\\LoadViewFromQuery.js"
    }
  ],
  "symbols": {
    "internal": {}
  },
  "trigger": [
    {
      "event": "onInitialized",
      "actions": [
        {
          "objectType": "Function",
          "active": true,
          "fn": "TcHmi.Functions.demo_multi_screen.LoadViewFromQuery",
          "fnParams": [],
          "asyncWait": true
        }
      ]
    }
  ],
  "actionTemplates": [],
  "languages": {
    "de-DE": "Localization\\de-DE.localization",
    "en-US": "Localization\\en-US.localization"
  },
  "languageFallback": "",
  "disableLoadingOptimization": false,
  "creatorSettings": {
    "viewport": {
      "defaultWidth": 800,
      "defaultHeight": 600
    }
  },
  "packages": [
    {
      "name": "Beckhoff.TwinCAT.HMI.Controls",
      "basePath": "/Beckhoff.TwinCAT.HMI.Controls"
    },
    {
      "name": "Beckhoff.TwinCAT.HMI.Framework",
      "basePath": "/framework"
    },
    {
      "name": "Beckhoff.TwinCAT.HMI.Functions",
      "basePath": "/Beckhoff.TwinCAT.HMI.Functions"
    }
  ]
}
